package com.dairy.exception;

public enum CustomException {

    USER_ALREADY_EXISTS ,
    REQUIRED_FIELD_MISSING, INVALID_PARAMETERS, PRODUCT_SAVE_FAILED, PRODUCT_NOT_FOUND, NO_PRODUCTS_CURRENTLY_AVALIABLE, OUT_OF_STOCK, PRODUCT_NOT_AVALIABLE, FATAL_EXCEPTION, INVALID_USER, INVALID_COUPON_CODE, COUPON_EXPIRED;
}
